### ISSUE TITLE
有些设备没有识别出来

### ISSUE THREAD

**Issue by jay1943000** [hasscc/yeelight-pro#2]
1. S21智能墙壁开关
2. S21全面屏开关
3. S21窗帘电机
4. S20双路控制器

**Comment by al-one** [comment]
请添加这个微信。
<img src="https://user-images.githubusercontent.com/4549099/161735971-0540ce1c-eb49-4aff-8cb3-3bdad15e22f7.png" alt="xiaomi miot weixin group" width="100">
> 备注“Yeelight Pro”

**Comment by jay1943000** [comment]
新版已经接入,辛苦al-one了
