### ISSUE TITLE
无法连接网关

### ISSUE THREAD

**Issue by socekin** [hasscc/yeelight-pro#5]
<img width="383" alt="image" src="https://user-images.githubusercontent.com/874961/230738982-f7649d05-dcd2-454d-94e3-53d698b4c995.png">

通过HACS安装插件后，输入网关IP地址无法连接。网关是连接在主路由192.168.2.1，网关IP 192.168.2.18

**Comment by casatift** [comment]
yeelight pro APP中查看网关是否已开启局域网通讯功能

**Comment by socekin** [comment]
感谢，开启后正常了
